[package]
name = "paper-ffx-datafusion"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
arrow-array = "=59.2.0"
arrow-schema = "=59.2.0"
datafusion = { git = "https://github.com/GreptimeTeam/datafusion", rev = "4bd567a884dcbfd89d0f0a7859ef8367e38fff97", default-features = false, features = ["sql"] }
futures = "=0.3.31"
tokio = { version = "=1.52.3", features = ["macros", "rt-multi-thread"] }

[profile.dev]
debug = 0

[profile.test]
debug = 0

[[bin]]
name = "paper-ffx-datafusion"
path = "src/main.rs"
